[tool.poetry]
name = "poc-langchain"
version = "0.1.0"
description = "Assistant Email + Calendrier Automatique avec LangChain et Streamlit"
authors = ["jabo"]
readme = "README.md"
packages = [
    { include = "my_assistant" }
]

[tool.poetry.dependencies]
python = "^3.10"
streamlit = "^1.53.1"
pydantic = "^2.12.5"
langchain = "^1.2.7"
langchain-ollama = "^1.0.1"
python-dotenv = "^1.2.1"

[tool.poetry.dev-dependencies]
black = "^26.1.0"
flake8 = "^7.3.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
